### ISSUE TITLE
Rebrand lab code package naming

### ISSUE THREAD

**Issue by billkable** [platform-acceleration-lab/core-spring-code#11]
Migrate away from `io.pivotal`

Options: 

- com.vmware.tanzu-learning
- com.vmware.tanzulearning
- io.spring.learning
- io.spring.training

**Comment by ndwinton** [comment]
I didn’t think package names could have a hyphen in them?

You might also consider io.spring.learning, or com.VMware.tanzu.learning, I
guess.

**Comment by billkable** [comment]
@ndwinton @joemoore I think we should use spring package names, maybe like `io.spring.learning`, and keep VMware branding out of the core content (except maybe the site footer).

Interested in your thoughts...

**Comment by joemoore** [comment]
Agreed, good point.

**Comment by billkable** [comment]
Solicit feedback from Spring Team, ETA March 18th.

**Comment by billkable** [comment]
Running with `io.spring.training` to follow the spring.io site: https://spring.io/training

**Comment by billkable** [comment]
Acceptance of this issue is implicit after acceptance of all lesson rebranding issues _*for spring boot 2.6.4 and spring 5.3.16_.
