### ISSUE TITLE
Exclude git history (.git), .github and tc server configs from the downloadable labs artefact

### ISSUE THREAD

**Issue by patbaumgartner** [platform-acceleration-lab/core-spring-code#16]
During the current course i realised that the commit history is available in the labs zip file. 
This is something we probably want to remove from the artefact like the .github folder.

**Comment by billkable** [comment]
@patbaumgartner yes, we will definitely pull out the local git history - does not make sense for the current state of the core spring course.

The .github directory contains the verification testing workflow run.  Might there be value in keeping it if the student elects to save their lab as a git remote repo?

**Comment by patbaumgartner** [comment]
@billkable I have no bad feelings if you leave the .github folder with its config in the zip file. 
I just don't see a case where this could be useful. Never had a student who pushed the labs to github.

Something I came across too, was the tc server configs. Most if not all of my students are using IntelliJ anyway.
The tc server configs are useless and also outdated since tc server is currently on version 4.

Best,
Patrick

**Comment by billkable** [comment]
Handing this with two separate updates:

- [x] Remove TC Server
- [x] Remove Github workflow - this will require modification to the pipeline to remove it.

**Comment by billkable** [comment]
Note that shipkin generated codebases include the git history, and (without modifying the source for the shipkin generator) the history cannot be suppressed.

Given that the student does not care about the git history, the link in Spring Academy will point to the release source artifact, not the shipkin generated one.
