### ISSUE TITLE
Handle deprecation errors in 38-rest-ws-solution

### ISSUE THREAD

**Issue by billkable** [platform-acceleration-lab/core-spring-code#21]
Several deprecations in 38-rest-ws-solution, 

the `exchange` method is favor of `exchangeToMono` or `exchangeToFlux` : https://github.com/vmware-tanzu-learning/core-spring-code/blob/main/lab/38-rest-ws-solution/src/test/java/accounts/client/AccountWebClientTests.java#L56

**Comment by felipeg48** [comment]
Fixing Solution Lab for now with the following: `exchangeToMono(response -> Mono.just(response))`
Also adding missing annotation that are required now.

**Comment by felipeg48** [comment]
Fixing Solution Lab for now with the following: `exchangeToMono(response -> Mono.just(response))`
Also adding missing annotations that are required now.
